trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: pwsh -File './deploy.ps1' -Staging $(Build.ArtifactStagingDirectory)
  displayName: 'Copy and Download UDs'

  # Publish Pipeline Artifact
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'ChatRoom'
    targetPath: $(Build.ArtifactStagingDirectory)